export interface JobCard{
  id: number,
  inspectionFee?: number,
  inspectionDate?: any,
  repairFee?: number,
  repairDate?: any,
  quotationDate?: any,
  certificateNumber?: string,
  salesPerson?: string,
  address: {
    unitNumber?: number,
    complexName?: string,
    streetNumber: number,
    street: string,
    suburb: string,
    city: string,
    postCode: number
  },
  dateJobCardCreated: any,
  ownerSellerName: string,
  ownerContact: string,
  buyerName?: string,
  buyerContact?: string,
  certificateTo?: string,
  additionalTo?: string,
  estateAgent?: string,
  tenant?: string,
  instructionsFrom?: string,
  repairDateTime?: any,
  jobCardNotes?: string,
  invoiceDetails?: any,
  inspectionType: any,
  registrationDate?: any
}